[package]
name = "gemini-ai-rust"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A Rust client for the Google Gemini AI API"
license = "MIT"

[dependencies]
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0.9"
tokio = { version = "1.0", features = ["full"] }

[dev-dependencies]
dotenv = "0.15"
